apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kossal.io-certificate
spec:
  secretName: kossal.io-certificate
  issuerRef:
    name: letsencrypt-dev-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.kossal.io"
  dnsNames:
    - "kossal.io"
    - "*.kossal.io"