# Default values for query-editor-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: query-editor-api # Set by --set image.repository
  pullPolicy: IfNotPresent
  tag: "0.0.1" # Set by --set image.tag
  securityContext: {}

env:
  configMap:
    - name: environment-config
      key: ENVIRONMENT
    - name: metabase-config
      key: METABASE_API_HOST
  secrets:
    - name: metabase-secrets
      key: METABASE_USER
    - name: metabase-secrets
      key: METABASE_PASSWORD

# imagePullSecrets:
#  - name: do-registry

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kossal.io
      paths:
      - path: /api
        pathType: ImplementationSpecific
  tls:
    - secretName: kossal.io-certificate
      hosts:
        - "*.kossal.io"

resources:
  limits:
    cpu: 1
    memory: "1.3G"
  requests:
    cpu: 0.5
    memory: "256M"


readinessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 20
  failureThreshold: 10
livenessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 20
  failureThreshold: 10

serviceAccount:
  create: false

autoscaling:
  enabled: false